---
- name: add docker repo
  apt_repository:
    filename: dockerrepo
    repo: "deb https://download.docker.com/linux/ubuntu xenial stable"
- name: add docker repo key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 0EBFCD88
- name: update apt cache
  shell: apt update
- name: install docker-ce
  apt:
    name: docker-ce
    state: present
- group:
    name: docker 
    state: present
- user:
    name: ubuntu
    append: yes
    groups: docker    
- name: ensure base services are started
  service:
    name: docker
    state: started
    enabled: yes
